-- ============================================================
-- SCHEMA + SEED  –  Proyecto Integrador II
-- ============================================================

-- ── Tablas ───────────────────────────────────────────────────

create table usuarios (
  id                      integer generated by default as identity primary key,
  nombre                  text not null,
  correo                  text not null unique,
  rol                     text not null check (rol in ('Jefe TI', 'Técnico', 'Usuario')),
  area                    text not null,
  estado                  text not null default 'Activo' check (estado in ('Activo', 'Inactivo')),
  fono                    text,
  password_hash           text,
  debe_cambiar_contrasena boolean not null default false
);

create table disponibilidad (
  usuario_id      integer primary key references usuarios (id) on delete cascade,
  horario         text    not null default 'Sin horario asignado',
  tickets_activos integer not null default 0 check (tickets_activos >= 0),
  estado          text    not null default 'Libre' check (estado in ('Libre', 'Ocupado', 'Parcial'))
);

create table equipos (
  id        integer generated by default as identity primary key,
  codigo    text not null unique,
  nombre    text not null,
  area      text not null,
  tipo      text not null check (tipo in ('Laptop', 'Desktop', 'Impresora', 'Monitor')),
  estado    text not null default 'Operativo' check (estado in ('Operativo', 'En reparación', 'Dado de baja')),
  creado_en timestamptz not null default now()
);

create table tickets (
  id                 integer generated by default as identity primary key,
  descripcion        text not null,
  nombre_solicitante text not null,
  usuario_id         integer references usuarios (id) on delete set null,
  tecnico_id         integer references usuarios (id) on delete set null,
  equipo_id          integer references equipos  (id) on delete set null,
  prioridad          text not null check (prioridad in ('Crítico', 'Alto', 'Medio', 'Bajo')),
  estado             text not null default 'Abierto' check (estado in ('Abierto', 'En progreso', 'Cerrado', 'Cancelado')),
  creado_en          timestamptz not null default now(),
  check (tecnico_id is null or tecnico_id <> usuario_id)
);

create table evaluaciones (
  id           integer generated by default as identity primary key,
  ticket_id    integer  not null unique references tickets   (id) on delete cascade,
  tecnico_id   integer  not null         references usuarios (id),
  evaluador_id integer  not null         references usuarios (id),
  puntuacion   smallint not null check (puntuacion between 1 and 5),
  comentario   text not null default '' check (char_length(comentario) <= 500),
  creado_en    timestamptz not null default now()
);

create table sla_prioridades (
  id                   integer generated by default as identity primary key,
  nivel                text    not null check (nivel in ('Crítico', 'Alto', 'Medio', 'Bajo')),
  descripcion          text    not null,
  minutos_respuesta    integer not null check (minutos_respuesta    >= 0),
  minutos_resolucion   integer not null check (minutos_resolucion   >= 0),
  minutos_escalamiento integer not null check (minutos_escalamiento >= 0),
  actualizado_en       timestamptz not null default now()
);

create table articulos_conocimiento (
  id        integer generated by default as identity primary key,
  titulo    text not null,
  contenido text not null default '',
  categoria text not null check (categoria in ('Red', 'Hardware', 'Software', 'Impresoras', 'ERP')),
  autor_id  integer not null references usuarios (id),
  vistas    integer not null default 0 check (vistas >= 0),
  creado_en timestamptz not null default now()
);

-- ── Seed ─────────────────────────────────────────────────────

-- Usuario inicial (Jefe TI) — password: Admin123!
insert into usuarios (id, nombre, correo, rol, area, estado, password_hash) values
  (1, 'Ana Torres', 'ana.torres@empresa.pe', 'Jefe TI', 'TI', 'Activo',
   '$2b$10$RQI5CqLNa6kOz5hJsWjXTOknG.Igo26fH2ytOWP.WXTBetLCVNvUW');

-- Disponibilidad del usuario inicial
insert into disponibilidad (usuario_id, horario, tickets_activos, estado) values
  (1, 'Lunes a Viernes 08:00 - 17:00', 0, 'Libre');

-- SLA por defecto (los 4 niveles requeridos)
insert into sla_prioridades (nivel, descripcion, minutos_respuesta, minutos_resolucion, minutos_escalamiento) values
  ('Crítico', 'Falla total que impide operar al negocio',          15,  240,  60),
  ('Alto',    'Falla grave que afecta a varios usuarios',          30,  480,  120),
  ('Medio',   'Falla parcial con impacto moderado',                60,  1440, 240),
  ('Bajo',    'Solicitud de mejora o consulta sin urgencia',       240, 2880, 480);

-- Equipos
insert into equipos (id, codigo, nombre, area, tipo, estado, creado_en) values
  (1, 'LT-001', 'HP ProBook 450 G9',       'TI',           'Laptop',    'Operativo',    '2026-03-02T08:30:00Z'),
  (2, 'LT-014', 'Dell Latitude 5440',      'Contabilidad', 'Laptop',    'Operativo',    '2026-03-05T10:15:00Z'),
  (3, 'DS-007', 'OptiPlex 7010 SFF',       'TI',           'Desktop',   'Operativo',    '2026-03-06T09:00:00Z'),
  (4, 'DS-012', 'ThinkCentre M70q',        'Ventas',       'Desktop',   'Operativo',    '2026-03-10T14:45:00Z'),
  (5, 'DS-019', 'ProDesk 400 G7',          'RRHH',         'Desktop',   'Dado de baja', '2026-02-18T11:20:00Z'),
  (6, 'IM-003', 'HP LaserJet Pro M404',    'Ventas',       'Impresora', 'Operativo',    '2026-02-24T08:50:00Z'),
  (7, 'IM-008', 'Epson EcoTank L3250',     'RRHH',         'Impresora', 'Operativo',    '2026-03-01T16:05:00Z'),
  (8, 'MN-021', 'Dell UltraSharp U2723QE', 'TI',           'Monitor',   'Operativo',    '2026-03-11T13:30:00Z'),
  (9, 'MN-026', 'LG 27UL500-W',            'Contabilidad', 'Monitor',   'Operativo',    '2026-03-12T09:40:00Z');

-- Artículos de conocimiento
insert into articulos_conocimiento (titulo, contenido, categoria, autor_id) values
  ('Cómo reconectar el WiFi corporativo',          'Desactiva y vuelve a activar el adaptador de red. Si el problema persiste, olvida la red y conéctate de nuevo con tus credenciales.', 'Red',        1),
  ('Mi computadora no enciende: pasos básicos',    'Verifica que el cable de poder esté conectado. Prueba con otro tomacorriente. Si tiene batería, intenta encender sin ella.',           'Hardware',   1),
  ('Cómo restablecer mi contraseña de correo',     'Ingresa al portal de autoservicio en https://reset.empresa.pe y sigue los pasos. Si no tienes acceso, contacta al área de TI.',        'Software',   1),
  ('Cómo agregar una impresora de red',            'Ve a Configuración → Impresoras y escáneres → Agregar impresora. Selecciona la impresora por su IP o nombre de red corporativo.',      'Impresoras', 1),
  ('Cómo recuperar mi acceso al ERP',              'Tu cuenta puede estar bloqueada por intentos fallidos. Contacta a TI con tu nombre completo y área para que reactiven tu usuario.',    'ERP',        1);

-- ── Ajuste de secuencias (para que el auto-increment continúe correctamente) ──

select setval(pg_get_serial_sequence('usuarios',               'id'), coalesce((select max(id) from usuarios),               0) + 1, false);
select setval(pg_get_serial_sequence('equipos',                'id'), coalesce((select max(id) from equipos),                0) + 1, false);
select setval(pg_get_serial_sequence('tickets',                'id'), coalesce((select max(id) from tickets),                0) + 1, false);
select setval(pg_get_serial_sequence('evaluaciones',           'id'), coalesce((select max(id) from evaluaciones),           0) + 1, false);
select setval(pg_get_serial_sequence('sla_prioridades',        'id'), coalesce((select max(id) from sla_prioridades),        0) + 1, false);
select setval(pg_get_serial_sequence('articulos_conocimiento', 'id'), coalesce((select max(id) from articulos_conocimiento), 0) + 1, false);